
[workspace]
resolver = "2"
members = [
    "packages/vetkd-notes-canister",
    "packages/vetkd-notes",
    "packages/vetkd-notes-client"
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
