[tasks.cargo-build]
script = [
    "cargo build"
]

[tasks.wasm-pack-build]
dependencies = ["cargo-build"]
script = [
    "cd packages/wasm-client && wasm-pack build"
]

[tasks.watch]
script = [
    "cargo watch -x \"make cargo-build\" -s \"make wasm-pack-build\""
]

[tasks.build]
dependencies = ["wasm-pack-build"]
