
[package]
name = "ic-vetkd-notes"
version = "0.1.6"
edition = "2021"
description = "ic vetkd notes implementation to be used inside of a canister"
license = "MIT"
repository = "https://github.com/shipstone-labs/vetkd-utils"
documentation = "https://shipstone-labs.github.io/vetkd-utils/ic_vetkd_notes"
exclude = [ "package.json", "node_modules", ".turbo", "turbo.json" ]
wasm-opt = false

[dependencies]
candid = "0.10.12"
ic-cdk = "0.17.1"
ic-cdk-macros = "0.17.1"
ic-stable-structures = "0.6.7"
lazy_static = "1.5.0"
serde_json = "1.0.135"
anyhow = "1.0.95"
serde = "1.0.217"
ic-types = "0.7.0"
hex = "0.4.3"
custom_debug = "0.6.2"
