
[package]
name = "ic-vetkd-notes"
version = "0.1.0"
edition = "2021"
description = "ic vetkd notes implementation to be used inside of a canister"
license = "MIT"
repository = "https://github.com/yourusername/ic-vetkd-notes"
documentation = "https://shipstone-labs.github.io/vetkd-notes"
exclude = [ "package.json", "node_modules", ".turbo", "turbo.json" ]

[dependencies]
candid = "0.9.11"
ic-cdk = "0.11.3"
ic-cdk-macros = "0.8.1"
ic-stable-structures = "0.6.4"
lazy_static = "1.4.0"
serde_json = "1.0.133"
anyhow = "1.0.75"
serde = "1.0.190"
ic-types = "0.7.0"
hex = "0.4.3"
custom_debug = "0.6.1"
