[package]
name = "vetkd-notes-client"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Enable `custom` feature of getrandom dependency. See lib.rs for more details.
getrandom = { version = "0.2", features = ["custom"], optional = true }
ic_bls12_381 = { workspace = true }
lazy_static = { workspace = true }
pairing = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
subtle = { workspace = true }
wasm-bindgen = { version = "0.2.84", optional = true }
wasm-bindgen-test = "0.3.47"
zeroize = { workspace = true }

[dev-dependencies]
hex = { workspace = true }

[features]
default = ["js"]
js = ["dep:wasm-bindgen", "dep:getrandom"]
