name: "Build"
on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🏗️ Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            target: wasm32-unknown-unknown
            components: rustfmt, clippy

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: 🏗️ Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "9.12.0"
      
      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.0.0'
          cache: 'pnpm'

      - name: 🏗️ Install dependencies
        run: pnpm install
    
      - name: 🏗️ Build
        run: pnpm build
