name: "Build"
on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            target: wasm32-unknown-unknown
      - run: cargo install wasm-pack cargo-make
      - run: cargo make
